name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., main, master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version your project requires

      # Install Yarn and dependencies
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      # Build the project
      - name: Build project
        run: yarn build
        env:
          PUBLIC_URL: /TradingGame # Set the PUBLIC_URL environment variable

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with the output directory of your build (e.g., dist, public, etc.)